Updating to version 0.5.2
flathub/com.github.cfcurtis.pdfstitcher pull request #1
Opened 2022-02-24 23:00 UTC by cfcurtis

I think I did this correctly, let me know if there is more required for updating versions.

I've also just finished automating release builds for Windows and MacOS, as well as publishing to PyPi. If there's a recommended procedure to add Flatpak builds to github actions, I'd be happy to do that as well.

One other thing - poking through the files I don't see anything about translations. I now have a setup.py script that handles compiling translation files, is there a way to switch the Flatpak build to use that?

2022-02-24 23:03 UTC, hfiguiere requested changes

2022-02-24 23:03 UTC, hfiguiere commented on com.github.cfcurtis.pdfstitcher.desktop
> +Version=0.5.2
Version here isn't the software version. It's the desktop file specification version.

it's the metainfo.xml you need to change.

2022-02-24 23:03 UTC, hfiguiere commented on com.github.cfcurtis.pdfstitcher.json
>                    "sha256": "77cd9f3d1e4559e8ea8d3c27fb36a7dcee8824d69d0f6457fb9b2a2c395909c8",
you also need to change the checksum to the new one.

2022-02-24 23:14 UTC, hfiguiere commented
as stated you should update the metainfo.xml to update the version number.

2022-04-27 16:44 UTC, cfcurtis commented
Up to v0.6.1 now, closing this one. Need a better workflow.

2022-04-27 16:44 UTC, closed without merging